title: My Portfolio
description: A showcase of my projects and skills
baseurl: ""
url: ""

# Build settings
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
